### ISSUE TITLE
Check what the cutoff field in the broadcast form is doing

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-ui#1222] opened 2023-02-02 14:55 UTC

**Comment by oliver-sanders** [comment] 2023-02-06 15:39
The "cutoff" field gets populated because AOTF tries to be helpful and fill in every field that it can. The cutoff field is a `CyclePoint` and AOTF knows the cycle point for the task you clicked on to open the broadcast menu...

We could just change the type of the field back to `String`, however, schema changes introduce compatibility issues. Older versions of the UIS would not support broadcasts to newer versions of cylc-flow and vice-versa.

This is exactly the sort of thing that AOTF was designed to avoid, however, at present we don't load the schema of each workflow individually, we load the schema of the UIServer so the UIS and workflow schemas must match. This should be addressed in future, it just hasn't been done yet, here's an issue to track this - https://github.com/cylc/cylc-ui/issues/1225. 

Until this is done, schema changes will break compatibility across UIServer versions.

**Closed** 2023-02-08 15:59 UTC
Labels: investigation

**Comment by MetRonnie** [comment] 2023-02-13 11:22
Note: the cutoff field only applies to the "expire" mode
