### ISSUE TITLE
Advanced sorting (tree view)

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#588] opened 2021-01-28 21:19 UTC
REF: https://github.com/cylc/cylc-ui/pull/579#pullrequestreview-578574908

**Pull requests welcome!**

**Comment by kinow** [comment] 2021-01-28 21:24
Thanks @hjoliver 

The tree is now using `sortedIndex` of Lodash. Which works great, doing a binary-search to locate the next index to add an item, which will keep the array sorted.

The issue is that it doesn't do a `localeCompare`, so we have `0, 10, 1, 2, 3...` (10 is before/after `1`, don't remember the order in JS). I will take a look later to see if I can use `sortedIndex` but compare values with `localeCompare`, or if we need another solution. Shouldn't be too hard to fix.

**Comment by kinow** [comment] 2021-01-28 21:32
And a note to self: I think there is a part of the sorting done in reverse order. I think I called `.reverse()` on a list, but maybe `sortedIndexBy` + a functional that instead of using the value, uses something like `-value` could be an alternative to avoid reversing the collection.

**Comment by kinow** [comment] 2021-05-11 01:37
Fixed in #665 (sorry, ended up creating a separate issue)

**Closed by kinow** 2021-05-11 01:37 UTC
Labels: bug, good first issue, help wanted
