### ISSUE TITLE
Avoid data duplication in added deltas

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-ui#661] opened 2021-05-04 05:43 UTC
**Describe exactly what you would like to see in an upcoming release**

We have added cyclepoints, family proxies, task proxies, and jobs being received twice, once in `deltas.added.workflow.$KEY` (where key is each of these node types), and again in `deltas.added.$KEY`.

**Additional context**

From Element today, issue raised by @hjoliver 

**Pull requests welcome!**

**Comment by hjoliver** [comment] 2021-05-24 03:44
I think `deltas.added.workflow.$` was added to handle the initial burst, because it only gets populated then (and is then a duplicate of `deltas.added.$`)

It seems to me we should be able to ditch the whole `deltas.added.workflow` part because the initial burst is still just a delta, isn't it? (It's still the difference between the new state and the previous state, but in this case previous state is null). 

Presumably if the tree is empty when a delta is received, then:
- if `deltas.added` is present and `deltas.updated` and `deltas.pruned` are not, it must be an initial burst, and we should construct the tree
- otherwise error

Or have I misunderstood something?

**Comment by kinow** [comment] 2021-05-24 04:36
What you said makes sense to me, but I am not sure if the initial data burst is just a delta? Say I subscribe to a query now, and at this moment the pool has (sorry if being vague, I have only high level understanding of the pool):

- 1 task proxy
- 2 job of that task proxy
  * job `1` failed
  * retry policy triggered second job `2` that is in `submitted` state

I think the subscription in GraphQL normally gives your entries of some data stream (like a database, log file, messaging system, etc) that changed after you susbcribed to the query. So if I subscribe to a query now, I don't need to receive anything.

Then the second job succeeds. Now I think I should receive the first response in my GraphQL subscription, something like

```json
{
  deltas: {
    updated: {
      id: "kinow|five|1|foo|2,
      state: "succeeded",
      ...
  }
}
```

Here the UI doesn't know about the cycle point, or the task proxy. So the job cannot be added to the tree, unless I create each node from the updated delta.

I think that's why we introduced the initial data burst. And I think that's why Apollo Client has the `subscribeToMore`, where you fetch data with a query (essentially doing the same as our initial data burst), and updates your data with a subscription that receives whatever changed after your subscription was created.

**Closed** 2021-07-05 03:04 UTC
Labels: efficiency, good first issue, hacktoberfest, help wanted
