### ISSUE TITLE
Filter bar should be fixed to top of tree window

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-ui#836] opened 2021-11-04 14:48 UTC
**Describe exactly what you would like to see in an upcoming release**

I think that the filter bar should remain visible in the tree view as you scroll down, because:
- Users will probably want to see what they are filtering on.
- Users might want to change their filters without scrolling to the top of the tree view.

Current behaviour:
![image](https://user-images.githubusercontent.com/26465611/140335298-ed731378-9d6b-4557-84d9-77e1b18526ba.png)
![image](https://user-images.githubusercontent.com/26465611/140335376-ab40c635-cebf-45e9-b5ba-a75412b045ea.png)

**Pull requests welcome!**

**Comment by hjoliver** [comment] 2021-11-04 20:48
Agreed, good suggestion :+1:

**Comment by oliver-sanders** [comment] 2021-11-08 11:57
This is covered by design issue #471 which describes a "view toolbar component" which is pinned.

**Comment by hjoliver** [comment] 2021-11-08 18:50
Ah right, good. I'll close this as a duplicate.

**Closed by hjoliver** 2021-11-08 18:50 UTC
Labels: enhancement, good first issue, question
