### ISSUE TITLE
tree: showing more cycle points than expected

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#496] opened 2020-09-16 12:55 UTC
[UPDATE: this issue will be made irrelevant - and closed - by n-distance windowing]

The tree view seems to be displaying more cycle points than it should. GraphQL seems to show the expected view window. My guess is that this is either:

* The tree view not removing nodes correctly.
* The UIS not sending the relevant "removed" deltas.

Here's an example to reproduce the issue:

```ini
[scheduling]
    initial cycle point = 1
    cycling mode = integer
    [[graph]]
        P1 = """
            a[-P1] => a
            b[-P2] => b
            c[-P3] => c
            d[-P4] => d
            e[-P5] => e
            f[-P6] => f
        """

[runtime]
    [[root]]
        script = sleep 1
```

And a demonstration of the issue:

![sorting](https://user-images.githubusercontent.com/16705946/93340004-2dda1700-f824-11ea-966c-f827a6d3a846.gif)

**Comment by kinow** [comment] 2020-09-17 01:37
Reproduced the issue. Not sure if it's in the UI or UIS. @dwsutherland is there any obvious reason for the cycle points to linger for so long?

My guess is that deltas to prune the tree are arriving, but maybe not as fast as we expected? Maybe there's some constraint in the backend that needs to be sorted out before the delta can be sent to the UI?

The UI removes the cycle point once the prune delta for the `root` family of that cycle point is received. In the cases of bugs in the UI, what I've seen are cycle points that are never removed, causing the elements to grow over time. In this case, it appears to be always displaying 7 cycle points.

**Comment by kinow** [comment] 2020-09-17 01:39
(as for why 7, I **guess** it has something to do with current cycle point, plus -P1, plus -P2, plus -P3..., plus -P6? So 7 cycle points in total?)

**Comment by hjoliver** [comment] 2020-09-17 04:54
I was going to suggest this probably just reflects the current(/interim) datastore pruning, keeping whole cycles with any active task present, and the intercycle dependencies in the example flow above.  But I guess it is the discrepancy between delta-driven tree and whole state (not deltas) that is weird?

**Comment by oliver-sanders** [comment] 2020-09-17 11:11
Might be worth testing with the new n=1 PR, with a bit of luck that'll fix it.

**Comment by hjoliver** [comment] 2020-09-17 11:56
I just tried that - I think David hasn't implemented pruning yet on the n=1 branch; and it also seems to break the web UI - I only get the first 8 cycles forever.  (However it's late, I might have screwed up).

**Comment by kinow** [comment] 2020-09-17 22:34
If that's the case this issue could be transferred over to cylc-flow or cylc-uiserver repo I think

**Comment by hjoliver** [comment] 2020-09-18 00:58
Yes, I think it is a datastore issue, and not unexpected given the current stage of development. Probably doesn't need a new issue as the current n=1 window PR will presumably address this.

**Comment by hjoliver** [comment] 2020-09-18 00:59
(@dwsutherland should be able to confirm that the extra cycle points seen above, for the given flow, make sense for the current datastore).

**Comment by oliver-sanders** [comment] 2020-09-18 09:07
The extra cycles don't appear in the GraphQL subscription (see GIF in issue description) so this *might* not be to do with pruning.

**Comment by kinow** [comment] 2020-09-22 21:16
> The extra cycles don't appear in the GraphQL subscription (see GIF in issue description) so this _might_ not be to do with pruning.

I think they show, but in a different time. They must be displayed in a `deltas.added` payload first. But the `deltas.pruned` that includes their ID's comes much later, so the UI doesn't remove them.

It would be a bug in the UI if the `deltas.pruned` were received, but the cycle/families were not removed (in which case, we would have accumulated cycle points). But since we have a constant number of cycle points in the UI, my guess is that the UIS data store needs some change to send the pruned deltas sooner (I'm guessing that's what we want, though I don't fully understand SoD/deltas store/etc to say precisely when a task should disappear from UI & UIS)

**Comment by hjoliver** [comment] 2020-09-22 23:32
Oliver's gif above shows the full (not deltas) feed, so (from your comment @kinow ) this might indicate a problem with the deltas rather than the full datastore.

**Comment by kinow** [comment] 2020-09-22 23:39
> Oliver's gif above shows the full (not deltas) feed, so (from your comment @kinow ) this might indicate a problem with the deltas rather than the full datastore.

Sorry, you are correct Hilary.

**Comment by dwsutherland** [comment] 2020-09-22 23:42
Looks irrelevant once the [n-distance](https://github.com/cylc/cylc-flow/pull/3811) window goes in...

Because at the moment cycles are pruned only when no edges extend from it into the active set of cycles, and all tasks are generated for active cycles.

Some may be ghost and not show up in the tree at the moment

**Closed** 2020-11-11 02:14 UTC
Labels: bug
