### ISSUE TITLE
resizing the draw very difficult

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#1902] opened 2024-08-14 08:55 UTC
When the draw is scrolling (i.e. when you have more workflows than can fit vertically), it can be very difficult to resize the draw because the scroll bar gets in the way of the very narrow resize margin.

**Comment by MetRonnie** [comment] 2024-08-14 10:54
Duplicate of #1415?

**Closed** 2024-08-14 10:57 UTC
Labels: UX/UI
