### ISSUE TITLE
tree view: on error, wrong (last) suite's tasks listed

### ISSUE THREAD

**Issue by sadielbartholomew** [cylc/cylc-ui#103] opened 2019-07-06 14:30 UTC
For a suite where the tree view page at ``.../suites/<suite-name>`` raises an error giving a 'this is undefined' error box (at least), the task listing below will display (perhaps in some subset of circumstances) the tasks from the previous suite accessed via the UI (under some endpoint ``.../suites/<other-suite-name>``). This might be clearer by example, as given below.

We should ensure a blank table is shown upon any error, & also make sure there is no continued querying of data on previous suites.

#### Example: context observed

I was running three suites, all of which were picked up by the UI:

![ds-final-upload](https://user-images.githubusercontent.com/30274190/60757211-687cd880-9fff-11e9-890f-75334d782dfd.png)

& there was some error which meant that for one suite (``singlesuite-app-domingo``) the task data was not coming through (I won't raise that as an Issue itself for now, as it may turn out to be because the data provision is not completed to that extent yet).

This gave a 'this is undefined box', which spawned as outlined in #91. But the task table was not empty; it showed the same data as shown under either of the other suite's tree views, depending on which was the one previously viewed, i.e. it either showed this (as for the tree view for ``testbase-sleepforever``):

![ds-final-2](https://user-images.githubusercontent.com/30274190/60757210-687cd880-9fff-11e9-8e50-b9d471f39fd9.png)

or this (as for ``consolidation-tutorial``):

![ds-final-err-copy](https://user-images.githubusercontent.com/30274190/60757212-687cd880-9fff-11e9-92be-14f4f98eca58.png)

**Comment by kinow** [comment] 2019-07-07 21:56
Once the #91 at least the multiple errors should be gone.

Now about the tasks... that's an excellent point @sadielbartholomew ... when there is an issue retrieving the tasks... should we

- leave the tasks as is, and wait for the next update to see if that works?
- remove the tasks from previous execution?
- maybe gray out the whole area marking it as "you can't use it because something happened" ? 

I believe we discussed using this similar gray-area approach for loading or errors, in the design session a few days ago.

**Comment by hjoliver** [comment] 2019-07-08 17:51
I think we decided: if the UI fails to get data updates (in the WebSocket world,I guess this would imply detecting that the connection broke?) gray out the view and put up an alert/warning message.  We shouldn't just display the last-received status as normal, because the user might attempt to do things based on that outdated status (e.g. kill or retrigger tasks).

**Comment by kinow** [comment] 2019-07-08 17:55
Right. So we would gray out the tree view, leaving the tasks as they were, and once the websocket or polling works, it would go back to normal and keep updating the tree view. Does that sound like a good way to handle errors for this view? And ai believe the graph view would have the same behaviour.

**Comment by hjoliver** [comment] 2019-07-08 18:03
Yes, sounds good - same for all views.

**Comment by hjoliver** [comment] 2019-07-08 18:05
> in the WebSocket world,I guess this would imply detecting that the connection broke?) gray out the view and put up an alert/warning message

Or should we have a heart-beat ticker in the WebSocket connection, to indicate a healthy connection even when nothing is happening in the workflow?

**Comment by kinow** [comment] 2019-07-08 18:07
Sorry, closed by accident.

The heart beat could be part of the websocket protocol we will write. But I think that would be more related to https://github.com/cylc/cylc-ui/issues/93?

**Comment by kinow** [comment] 2019-07-08 18:11
(By protocol I mean the set of request-response that we will define to be used in the websockets... quite sure in JS or in some library they call it protocols... though that is a protocol, within websocket protocol, within TCP protocol, etc)

**Comment by sadielbartholomew** [comment] 2019-07-08 18:42
> Or should we have a heart-beat ticker in the WebSocket connection, to indicate a healthy connection even when nothing is happening in the workflow?

:+1 I really like this idea! If users have a long- or slow-running suite where state changes are rare, some visual indicator like this would reassure them when seeing the same data for a long time that it is because the suite hasn't evolved in that time period, rather than there being an issue in fetching data updates (or an unresponsive browser, etc.)!

**Comment by sadielbartholomew** [comment] 2019-07-08 19:35
Saying that, reading through a second time, I think you may have misinterpreted the Issue in your response https://github.com/cylc/cylc-ui/issues/103#issue-464859558, @kinow, but if so, definitely because I didn't explain it clearly (in which case, sorry). It's not that the tasks are being shown in a state that is not up-to-date, it is that the tasks for the *wrong* suite are being shown. They seem to persist in the table from the Tree View of the suite that was previously visited, somehow.

**Comment by hjoliver** [comment] 2019-07-08 21:01
Oh OK, yeah I didn't realize wrong-suite tasks were shown.

**Comment by kinow** [comment] 2019-07-08 21:05
Aahh, a heart beat for the suite status sounds useful too!

**Comment by kinow** [comment] 2019-09-17 02:10
Let's move it to 0.2. Would be grand if we can use the alpha release to try to reproduce this bug (which I suspect may have gone away in some of the commits that were pushed since this issue was created)

**Comment by kinow** [comment] 2020-01-06 06:59
Willing to close as cannot reproduce, especially after the tree component having changed so much. Any objections?

**Comment by oliver-sanders** [comment] 2020-01-06 19:49
I think this has been long solved by other changes. I don't think this can happen any more now that workflow IDs are props anyway.

**Closed by oliver-sanders** 2020-01-06 19:49 UTC
Labels: bug, hacktoberfest
