### ISSUE TITLE
deps: swap subscriptions-transport-ws for graphql-ws

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#1199] opened 2023-01-10 17:57 UTC
> subscriptions-transport-ws is no longer maintained
>
> Users should migrate to [graphql-ws](https://github.com/enisdenjo/graphql-ws), a newer actively-maintained implementation of a similar protocol.
>
> -- https://github.com/apollographql/subscriptions-transport-ws#subscriptions-transport-ws-is-no-longer-maintained

> The two libraries do not use the same WebSocket subprotocol, so you need to make sure that your server and clients all use the same library.
>
> -- https://www.apollographql.com/docs/react/data/subscriptions#choosing-a-subscription-library

>

**Comment by MetRonnie** [comment] 2023-01-17 11:36
Duplicate of #1028

**Closed by MetRonnie** 2023-01-17 11:36 UTC
Labels: dependencies
