### ISSUE TITLE
UI shows loading state forever if no workflows exist

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-ui#671] opened 2021-05-14 01:25 UTC
It should just show there are no workflows.

How we resolve this might depend on upcoming changes to show source workflows as well as installed ones.

![shot](https://user-images.githubusercontent.com/2362137/118206892-9498f880-b4b7-11eb-8c59-9cba98a98968.png)

**Comment by kinow** [comment] 2021-05-14 01:32
It's been a while since I last used the UI with no workflows. Well spotted!

**Comment by kinow** [comment] 2021-05-17 23:23
>How we resolve this might depend on upcoming changes to show source workflows as well as installed ones.

Even with source workflows, if you have an empty Cylc installation that would still be a problem (i.e. no workflows, no `cylc-run` directory, nada).

The issue is that at the moment we send a request to GraphQL. Once the request is received, we tell the client that it has loaded (and also apply deltas, or send data to Vuex store, etc).

When there are no workflows, if you run a query or subscription in GraphiQL, you should see the following:

![image](https://user-images.githubusercontent.com/304786/118567450-ed270900-b7c9-11eb-8385-305a60088756.png)

That's the same we have in Cylc UI's `WorkflowService` code at the moment. We are waiting for the backend to return anything, so that we can tell the views & components that loading the data has completed (at least once).

Not sure how to solve this. This is the Dashboard query:

```graphql
subscription {
  workflows {
    id
    name
    status
  }
}
```

If the subscription returned an empty array, then we would be able to use that as an indicator that loading is complete.

One possible solution would be to:

1. use a query instead of a subscription to fetch the UI data (like the initial data burst)
2. use ApolloClient's [`subscribeToMore`](https://www.apollographql.com/docs/react/data/subscriptions/#subscribing-to-updates-for-a-query) to update the data returned from the query above

That way we would have the data (or an empty array/object) in the query response, and update the UI data via the `subscribeToMore` subscription.

**Comment by dwsutherland** [comment] 2021-05-18 09:21
Maybe the UIS also needs an "initialBurst" like the workflows.

**Comment by oliver-sanders** [comment] 2021-06-10 12:20
I think when the first delta arrives (and is applied) from the subscription (i.e. the initial burst) we can say say that the view has loaded.

**Comment by kinow** [comment] 2021-06-27 21:13
@oliver-sanders the problem was that there was no initial data burst. We had 2 subscription queries that were forever waiting any data. But after reading your comment I immediately thought it would be fixed by the GScan pull request.

I've just now confirmed it's fixed by that pull request. The reason why that branch solves it, is that I've moved every subscription query that was using `subscription SomeQuery { workflow }` to `subscription SomeQueryDeltas { deltas { ... } }`.

So, as you pointed, now the initial data burst removes the loading state, and everything renders correctly when there are no workflows, as in the screenshot below.

![image](https://user-images.githubusercontent.com/304786/123559589-0d96aa00-d7f1-11eb-8bb5-fb330ba7032f.png)


Thanks!

**Closed** 2021-07-05 03:04 UTC
Labels: bug
